Ema cam photo
Sintrop/app-main-react pull request #55
Opened 2022-11-14 20:40 UTC by emanoeledevapps

2022-11-30 18:34 UTC, rav-andre requested changes
Legal ver o funcionamento do sistema, está no caminho certo.

Alguns pontos que necessitam revisão:

1) Uma vez tirada a foto, o usuário não consegue validar se a foto está ok antes. Implementar uma etapa anterior de permitir que o usuário veja se a foto está boa. Se sim, envia para o IPFS. Se não, reinicia o processo de tirar foto.

2) A imagem não está sendo renderizada.
O fluxo precisa ser:

foto webcam --> IPFS --> hash armanzenado na string proofPhoto --> front renderiznado pelo path do arquivo do ipfs

2022-12-15 14:08 UTC, rav-andre requested changes
1) Ao conectar um computador sem webcam, seria legal exibir uma mensagem do tipo "Por favor, conecte em um computador com webcam para prosseguir".  Ou então o que dá pra fazer é liberar a parte de fazer upload de imagem nessa etapa caso a pessoa conecte em uma máquina sem câmera. O que acha??

![image](https://user-images.githubusercontent.com/79549809/207706707-267301e5-b882-4d1a-a731-9f7280d186e4.png)

2) Um pequeno detalhe: A imagem pareceu ficar distorcida após tirar a foto. Aprece normal antes, e dps de salvar a foto distorce. Pq será que isso acontece?

![image](https://user-images.githubusercontent.com/79549809/207881649-eb061739-548f-47f8-a48f-a27f72c3f2d2.png)

![image](https://user-images.githubusercontent.com/79549809/207881780-09873f8a-eefa-46c1-9291-4564832a4ccd.png)

2022-12-15 20:57 UTC, emanoeledevapps commented
Certo, a parte da distorção já imagino o possível problema. Quanto a indisponibilidade da webcam, vou estudar um meio de mostrar ao usuário e liberar o cadastro!

2022-12-17 15:08 UTC, rav-andre approved these changes

2022-12-19 16:25 UTC, merged