create producer pool
Sintrop/app-main-react pull request #61
Opened 2022-12-22 14:25 UTC by emanoeledevapps

2022-12-22 15:25 UTC, rav-andre requested changes
Muito legal a implementação. Algumas sugestões de alteração:

1) Menu
![image](https://user-images.githubusercontent.com/79549809/209165250-ca419e67-8290-4a6f-a4ae-663dba3199b9.png)
Colocar producers na primeira posição.
Alterar o nome de 'Pools' para 'Token'.

2) Título da página
![image](https://user-images.githubusercontent.com/79549809/209165489-448179be-2718-4a3d-ada8-53cc4417b9af.png)

Alterar o texto para 'Producers distribution pool'

3) Dados extras
![image](https://user-images.githubusercontent.com/79549809/209165892-d59d0ef1-ace5-4452-8cff-05249562b001.png)
Adicionar o next approve in e a soma total do score dos produtores.
![image](https://user-images.githubusercontent.com/79549809/209166611-f5ef97e8-5fc9-43b7-9cee-b0990245c104.png)

O dado que precisa entrar como 'Producers total score' é o da linha 25 do producerContract 

4) Adicionar a coluna 'Score' na tabela com a informação do score do produtor. 

5) Corrigir link da wallet da tabela que não está clicável.

2022-12-22 17:03 UTC, emanoeledevapps commented
Qual seria o critério para o `Next Aprove In`? Ou já existe alguma função no contrato para isso?

O `score` do produtor na tabela, faz referência ao `Isa score` do produtor, certo?

2022-12-22 17:17 UTC, rav-andre commented
> Qual seria o critério para o `Next Aprove In`? Ou já existe alguma função no contrato para isso?
> 
> O `score` do produtor na tabela, faz referência ao `Isa score` do produtor, certo?

Isso, faz referência ao score do produtor. 

E sobre o next approve in, acredito que seja a mesma lógica do developers, que vem do contrato blockable. Vai ser igual do desenvolvedor no caso, só que chamando através do contrato ProducerPool.

2022-12-23 12:35 UTC, emanoeledevapps commented
Corrigido alguns problemas, faltando apenas:
--Redirecionamento quando clica na wallet dos usuários;
--Erro nas telas de `My account`.

2023-01-02 18:12 UTC, emanoeledevapps commented
Corrigido o erro de tela branca, ao entrar na página de `my account`.

2023-01-09 13:49 UTC, rav-andre approved these changes

2023-01-09 13:50 UTC, merged